algoritmo "Morty"
var
    reais, bitcoin: Real
inicio
    Escreval ("---------------Jogo do Rick and Morty...  ---------")
    Escreval ("--------------- Em uma galáxia distante...---------")
    Escreval ("Rick and Morty irão viajar para dentro da internet e precisam compra bitcoins")
    Escreval ("Quantos Reais vocês tem? R$")
    Leia(reais)
    bitcoinn <- real/30.000
    Escreva ("Você pode ter BTC", bitcoin)
fimalgoritmo
