algoritmo "lerMatriz"
var
   m:vetor[1..3, 1..2] de Inteiro
   c1, c2: inteiro

Inicio
      Para c1 <- 1 ate 3 faca
           Para c2 <- 1 ate 2 faca
           Escreva ("Digite um número na posição [", c1, ",", c2, "]: ")
           Leia (m[c1, c2])
           FimPara
      FimPara
      Para c1 <- 1 ate 3 faca
           Para c2 <- 1 ate 2 faca
           Escreva (m[c1,c2])
           FimPara
      Escreval( )
      FimPara

fimalgoritmo
