algoritmo "SomaParametrosReferencia"

var
   x, y: Inteiro

Procedimento Soma (var A, B: Inteiro)
inicio
      a <- a + 1
      b <- b + 2
      EscrevaL ("Valor de A = ", a)
      Escreval ("Valor de B = ", b)
      EscrevaL ("Soma de A + B = ", a+b)
FimProcedimento
inicio
      x <- 4
      y <- 8
      Soma (x, y)
      Escreval  ("Valor de X = ", x)
      Escreval  ("valor de Y = ", y)
fimalgoritmo
